### ISSUE TITLE
Ethnicity & Disease

### ISSUE THREAD

**Issue by AGCooper** [emory-libraries/ezpaarse-platforms#149]
#### Example:star::star: :
https://www-ethndis-org.proxy.library.emory.edu/edonline/index.php/ethndis

www.ethndis.org
ethndis.org

#### Priority: 
Medium

#### Subscriber (Library): 
Woodruff

#### ezPAARSE
Analysis: None
Trello: None

**Comment by lisahamlett** [comment]
TOC, HTML
https://www.ethndis.org:443/edonline/index.php/ethndis/issue/current
https://www.ethndis.org:443/edonline/index.php/ethndis/issue/view/35

ARTICLE, HTML
https://www.ethndis.org:443/edonline/index.php/ethndis/article/view/962
https://www.ethndis.org:443/edonline/index.php/ethndis/article/viewFile/962/1242/6212

**Comment by lisahamlett** [comment]
SEARCH;MISC
https://www.ethndis.org:443/edonline/index.php/ethndis/search/search?query=brain&authors=&title=&abstract=&galleyFullText=&suppFiles=&dateFromMonth=&dateFromDay=&dateFromYear=&dateToMonth=&dateToDay=&dateToYear=&dateToHour=23&dateToMinute=59&dateToSecond=59&discipline=&subject=&type=&coverage=&indexTerms=

TOC;HTML
https://www.ethndis.org:443/edonline/index.php/ethndis/issue/archive
https://www.ethndis.org:443/edonline/index.php/ethndis/issue/view/43

ABS;HTML
https://www.ethndis.org:443/edonline/index.php/ethndis/article/view/1118

ARTICLE;HTML
https://www.ethndis.org:443/edonline/index.php/ethndis/article/viewFile/1118/1636/8544

ARTICLE;PDF
https://www.ethndis.org:443/edonline/index.php/ethndis/article/download/1118/1634

NOTE: Use the above because this shows up with those and can be either PDF or HTML
https://www.ethndis.org:443/edonline/index.php/ethndis/article/view/1118/1634

[ethnicity_log.txt](https://github.com/emory-libraries/ezpaarse-platforms/files/3677288/ethnicity_log.txt)
