### ISSUE TITLE
Index of Medieval Art

### ISSUE THREAD

**Issue by eipeele** [emory-libraries/ezpaarse-platforms#170]
### Example:star::star: :
https://theindex-princeton-edu.proxy.library.emory.edu/

theindex.princeton.edu

### Priority: 
Medium

### Subscriber (Library): 
Woodruff

### ezPAARSE
Analysis: None
Trello: None

**Comment by lisahamlett** [comment]
Nothing on AnalogIST or Trello.

TOC, HTML
https://theindex.princeton.edu:443/s/Browse.action
https://theindex.princeton.edu:443/s/list/ListSubjects.action
https://theindex.princeton.edu:443/s/list/ListStylesCultures.action
https://theindex.princeton.edu:443/s/list/ListScripts.action

REF, HTML
https://theindex.princeton.edu:443/s/view/ViewSubject.action?id=415DBB9A-CC9F-4F63-B8DB-C1F9883D1483
https://theindex.princeton.edu:443/s/view/ViewStyleCulture.action?id=A32A1075-0AEF-4810-84DE-01A7C0159CC5
https://theindex.princeton.edu:443/s/view/ViewWorkOfArt.action?id=AA0D84A1-BC59-4AC8-9F37-070281DA1B5E
https://theindex.princeton.edu:443/s/view/ViewSubject.action?id=36248D0F-B490-4C22-AD21-8E527E364159
https://theindex.princeton.edu:443/s/view/ViewWorkOfArt.action?id=14F22B64-9F9B-4B8E-94A0-C1DC32342E54
https://theindex.princeton.edu:443/s/view/ViewScript.action?id=327E7D23-67FE-4C5A-9525-22BD80EA2A4D

SEARCH, HTML
https://theindex.princeton.edu:443/s/QueryWorkOfArt.action

**Comment by lisahamlett** [comment]
REF;HTML
https://theindex.princeton.edu:443/s/view/ViewLanguage.action?id=54F4F8DA-5A9E-426E-A7EB-5ADB7F2DE9DA
https://theindex.princeton.edu:443/s/view/ViewExternalReference.action?id=1EF3907B-BE7B-413E-9225-3DB764707EEC
https://theindex.princeton.edu:443/s/view/ViewExternalReferenceSource.action?id=89F634C8-75A3-4E73-B271-1654C633FD45
https://theindex.princeton.edu:443/s/view/ViewWorkOfArt.action?id=E512F406-A94C-4D7C-9611-165AA4054DA5
https://theindex.princeton.edu:443/s/view/ViewIllustrationType.action?id=D566D8A8-D87D-4696-A0A2-3F974F98501A 
https://theindex.princeton.edu:443/s/view/ViewLocation.action?id=30FAC388-6F0B-45D4-8381-37A1CF94AC75

SEARCH;HTML (many different actions)
https://theindex.princeton.edu:443/s/SearchWorksOfArt.action
https://theindex.princeton.edu:443/s/BrowseSubjectClassifications.action
https://theindex.princeton.edu:443/s/list/ListLanguages.action

NOTE: JPGs are set to not show in the logs because some websites have a lot of images that show in the log, so the images themselves are unparsable.

[index_log.txt](https://github.com/emory-libraries/ezpaarse-platforms/files/3677397/index_log.txt)
