### ISSUE TITLE
PressReader.com - Connecting people through news

### ISSUE THREAD

**Issue by eipeele** [emory-libraries/ezpaarse-platforms#195]
### Example:star::star: :
www.pressreader.com

### Priority: 
High

### Subscriber (Library): 
Woodruff

**Comment by lisahamlett** [comment]
http://ang.couperin.org/platforms/5a01d089850b09ec1bb4720d
https://trello.com/c/q6pxfR8m/436-pressreader-pr

This shows up weirdly in the logs and I couldn't find anything meaningful.

**Comment by lisahamlett** [comment]
When you open a new paper, whether it's from a search, a click, or whatever, the log looks like this.  Otherwise, there's nothing in it:

99.127.212.49 BPSyA1cAzEqKnfv lhamlet [11/May/2018:14:35:50 -0400] "GET http://www.pressreader.com:80/social/photo?photoid=gCLpn0pMhQmHi5yxwIUOSw%3d%3d&width=44&height=44 HTTP/1.1" 200 2007 http://www.pressreader.com.proxy.library.emory.edu/south-africa/business-day/20180511 Default+AlwaysProxy+MoreRestricted+Restricted+Unrestricted
99.127.212.49 BPSyA1cAzEqKnfv lhamlet [11/May/2018:14:35:50 -0400] "GET http://www.pressreader.com:80/social/photo?photoid=d9KPMDI8BPy4i6qNzRpEAw%3d%3d&width=44&height=44 HTTP/1.1" 200 1649 http://www.pressreader.com.proxy.library.emory.edu/south-africa/business-day/20180511 Default+AlwaysProxy+MoreRestricted+Restricted+Unrestricted
99.127.212.49 BPSyA1cAzEqKnfv lhamlet [11/May/2018:14:35:50 -0400] "GET http://www.pressreader.com:80/social/photo?photoid=hP5HGxeyt6iXio399672Ew%3d%3d&width=44&height=44 HTTP/1.1" 200 1844 http://www.pressreader.com.proxy.library.emory.edu/south-africa/business-day/20180511 Default+AlwaysProxy+MoreRestricted+Restricted+Unrestricted
99.127.212.49 BPSyA1cAzEqKnfv lhamlet [11/May/2018:14:35:50 -0400] "GET http://www.pressreader.com:80/social/photo?photoid=J3sLh%2bbGnLWv0pf5RAiKOw%3d%3d&width=44&height=44 HTTP/1.1" 200 1805 http://www.pressreader.com.proxy.library.emory.edu/south-africa/business-day/20180511 Default+AlwaysProxy+MoreRestricted+Restricted+Unrestricted
99.127.212.49 BPSyA1cAzEqKnfv lhamlet [11/May/2018:14:35:50 -0400] "GET http://www.pressreader.com:80/social/photo?photoid=k0qB1kifA2Qt4LPJmRnfiQ%3d%3d&width=44&height=44 HTTP/1.1" 200 1550 http://www.pressreader.com.proxy.library.emory.edu/south-africa/business-day/20180511 Default+AlwaysProxy+MoreRestricted+Restricted+Unrestricted
99.127.212.49 BPSyA1cAzEqKnfv lhamlet [11/May/2018:14:35:50 -0400] "GET http://www.pressreader.com:80/social/photo?photoid=XJIJwTruXiaPhOE84XvnfQ%3d%3d&width=44&height=44 HTTP/1.1" 200 1850 http://www.pressreader.com.proxy.library.emory.edu/south-africa/business-day/20180511 Default+AlwaysProxy+MoreRestricted+Restricted+Unrestricted
99.127.212.49 BPSyA1cAzEqKnfv lhamlet [11/May/2018:14:35:50 -0400] "GET http://www.pressreader.com:80/social/photo?photoid=wNb%2fF93C1ZGR1g9wMKc3EA%3d%3d&width=44&height=44 HTTP/1.1" 200 2006 http://www.pressreader.com.proxy.library.emory.edu/south-africa/business-day/20180511 Default+AlwaysProxy+MoreRestricted+Restricted+Unrestricted
99.127.212.49 BPSyA1cAzEqKnfv lhamlet [11/May/2018:14:35:50 -0400] "GET http://www.pressreader.com:80/social/photo?photoid=crbR6Z22hAh68Me%2bIeukMA%3d%3d&width=44&height=44 HTTP/1.1" 200 1868 http://www.pressreader.com.proxy.library.emory.edu/south-africa/business-day/20180511 Default+AlwaysProxy+MoreRestricted+Restricted+Unrestricted
99.127.212.49 BPSyA1cAzEqKnfv lhamlet [11/May/2018:14:35:50 -0400] "GET http://www.pressreader.com:80/social/photo?photoid=ljNuJz61y%2f%2f%2bXheK0BTghQ%3d%3d&width=44&height=44 HTTP/1.1" 200 1787 http://www.pressreader.com.proxy.library.emory.edu/south-africa/business-day/20180511 Default+AlwaysProxy+MoreRestricted+Restricted+Unrestricted
99.127.212.49 BPSyA1cAzEqKnfv lhamlet [11/May/2018:14:35:50 -0400] "GET http://www.pressreader.com:80/social/photo?photoid=8nWeH8suvgSHzfz%2bGZRzqw%3d%3d&width=44&height=44 HTTP/1.1" 200 1846 http://www.pressreader.com.proxy.library.emory.edu/south-africa/business-day/20180511 Default+AlwaysProxy+MoreRestricted+Restricted+Unrestricted
99.127.212.49 BPSyA1cAzEqKnfv lhamlet [11/May/2018:14:35:50 -0400] "GET http://www.pressreader.com:80/social/photo?photoid=9BrnUSNTqRsR88FB1Abr6w%3d%3d&width=44&height=44 HTTP/1.1" 200 1888 http://www.pressreader.com.proxy.library.emory.edu/south-africa/business-day/20180511 Default+AlwaysProxy+MoreRestricted+Restricted+Unrestricted
99.127.212.49 BPSyA1cAzEqKnfv lhamlet [11/May/2018:14:35:50 -0400] "GET http://www.pressreader.com:80/social/photo?photoid=1Xr30HJfd1L8ThmamI4fsA%3d%3d&width=44&height=44 HTTP/1.1" 200 1731 http://www.pressreader.com.proxy.library.emory.edu/south-africa/business-day/20180511 Default+AlwaysProxy+MoreRestricted+Restricted+Unrestricted
99.127.212.49 BPSyA1cAzEqKnfv lhamlet [11/May/2018:14:35:51 -0400] "GET http://www.pressreader.com:80/social/photo?photoid=jqzvRxxwp4aE4SmQ5SMs1A%3d%3d&width=44&height=44 HTTP/1.1" 200 1685 http://www.pressreader.com.proxy.library.emory.edu/south-africa/business-day/20180511 Default+AlwaysProxy+MoreRestricted+Restricted+Unrestricted
99.127.212.49 BPSyA1cAzEqKnfv lhamlet [11/May/2018:14:35:51 -0400] "GET http://www.pressreader.com:80/social/photo?photoid=0LnnuYukTMraX6d5VZoyOA%3d%3d&width=44&height=44 HTTP/1.1" 200 1803 http://www.pressreader.com.proxy.library.emory.edu/south-africa/business-day/20180511 Default+AlwaysProxy+MoreRestricted+Restricted+Unrestricted
99.127.212.49 BPSyA1cAzEqKnfv lhamlet [11/May/2018:14:35:51 -0400] "GET http://www.pressreader.com:80/social/photo?photoid=Q1HDrYd%2f2lbjA8YlweqX%2bw%3d%3d&width=44&height=44 HTTP/1.1" 200 1874 http://www.pressreader.com.proxy.library.emory.edu/south-africa/business-day/20180511 Default+AlwaysProxy+MoreRestricted+Restricted+Unrestricted
99.127.212.49 BPSyA1cAzEqKnfv lhamlet [11/May/2018:14:35:51 -0400] "GET http://www.pressreader.com:80/social/photo?photoid=YQi6M%2bPEA%2bAn3zXAGAl%2b5w%3d%3d&width=44&height=44 HTTP/1.1" 200 2099 http://www.pressreader.com.proxy.library.emory.edu/south-africa/business-day/20180511 Default+AlwaysProxy+MoreRestricted+Restricted+Unrestricted
99.127.212.49 BPSyA1cAzEqKnfv lhamlet [11/May/2018:14:35:51 -0400] "GET http://www.pressreader.com:80/social/photo?photoid=1iKJMpQe1nu7yY%2b3Obp0nQ%3d%3d&width=44&height=44 HTTP/1.1" 200 1925 http://www.pressreader.com.proxy.library.emory.edu/south-africa/business-day/20180511 Default+AlwaysProxy+MoreRestricted+Restricted+Unrestricted
99.127.212.49 BPSyA1cAzEqKnfv lhamlet [11/May/2018:14:35:51 -0400] "GET http://www.pressreader.com:80/social/photo?photoid=IU2jgCmqvZiopP1FnZ9DYg%3d%3d&width=44&height=44 HTTP/1.1" 200 1966 http://www.pressreader.com.proxy.library.emory.edu/south-africa/business-day/20180511 Default+AlwaysProxy+MoreRestricted+Restricted+Unrestricted
99.127.212.49 BPSyA1cAzEqKnfv lhamlet [11/May/2018:14:35:51 -0400] "GET http://www.pressreader.com:80/social/photo?photoid=7bE%2fEoQT40nwBg%2fPlpcydw%3d%3d&width=44&height=44 HTTP/1.1" 200 1848 http://www.pressreader.com.proxy.library.emory.edu/south-africa/business-day/20180511 Default+AlwaysProxy+MoreRestricted+Restricted+Unrestricted
99.127.212.49 BPSyA1cAzEqKnfv lhamlet [11/May/2018:14:35:51 -0400] "GET http://www.pressreader.com:80/social/photo?photoid=sfJsazGwzKDhcl5MGOPZQQ%3d%3d&width=44&height=44 HTTP/1.1" 200 1779 http://www.pressreader.com.proxy.library.emory.edu/south-africa/business-day/20180511 Default+AlwaysProxy+MoreRestricted+Restricted+Unrestricted
99.127.212.49 BPSyA1cAzEqKnfv lhamlet [11/May/2018:14:35:51 -0400] "GET http://www.pressreader.com:80/social/photo?photoid=NdUza1Nof8%2bdkJuKTY76Og%3d%3d&width=44&height=44 HTTP/1.1" 200 1976 http://www.pressreader.com.proxy.library.emory.edu/south-africa/business-day/20180511 Default+AlwaysProxy+MoreRestricted+Restricted+Unrestricted
99.127.212.49 BPSyA1cAzEqKnfv lhamlet [11/May/2018:14:35:51 -0400] "GET http://www.pressreader.com:80/social/photo?photoid=oExuKmzr5xnd1tWnB8ZF3g%3d%3d&width=44&height=44 HTTP/1.1" 200 1777 http://www.pressreader.com.proxy.library.emory.edu/south-africa/business-day/20180511 Default+AlwaysProxy+MoreRestricted+Restricted+Unrestricted

**Comment by AGCooper** [comment]
http://www.pressreader.com:80/category/business/en/us

http://www.pressreader.com:80/category/editorial/en/us

http://www.pressreader.com:80/category/sports/en/us

I had to refresh the page to get those into the log, so I don't know what is going on with this ...

**Comment by AGCooper** [comment]
@eipeele I'm running into the same thing @lisahamlett was (nothing useful in the logs). Can you take a look before we move this to the parking lot?

**Comment by lisahamlett** [comment]
Can we maybe just do something that says they accessed it?  So we can see how many users/sessions opened the thing?  I'd hate to not have _anything_ for it at all...

**Comment by AGCooper** [comment]
Why? It's not like there is anything there. It hasn't loaded in 2 days. But besides bitching... how about the authentication link: http://www.pressreader.com:80/Authentication/ConfirmCookies?_=1528393102616

**Comment by lisahamlett** [comment]
Works for me.
