### ISSUE TITLE
Netter Reference (Elsevier)

### ISSUE THREAD

**Issue by eipeele** [emory-libraries/ezpaarse-platforms#214]
### Example:star::star: :
http://netterreference.com.proxy.library.emory.edu/

### Priority: 
Low

### Subscriber (Library): 
Health

### ezPAARSE:
Analysis: None

**Comment by lisahamlett** [comment]
Authenticates and drops proxy.  Probably will migrate to Science Direct at some point, so don't put hours of work into this one -- just get what you can.
Also, double check that subscription isn't already through Science Direct, because if it has migrated by the time we get to it, we can just close the issue and not worry about it.

**Comment by lisahamlett** [comment]
This is now under Clinical Key.
