### ISSUE TITLE
Dyabola

### ISSUE THREAD

**Issue by eipeele** [emory-libraries/ezpaarse-platforms#234]
### Example:star::star: :
http://www.dyabola.de.proxy.library.emory.edu/en/indexfrm.htm?page=http://www.dyabola.de/

www.dyabola.de
dyabola.de

### Priority: 
Medium

### Subscriber (Library): 
Woodruff

### ezPAARSE
Analysis: http://ang.couperin.org/platforms/to_be_completed/

**Comment by lisahamlett** [comment]
The only things that can be parsed for this are connections because it drops proxy for IP:
http://www.dyabola.de/de/indexfrm.htm?page=http://www.dyabola.de/Index_de.htm
http://www.dyabola.de/en/indexfrm.htm?page=http://www.dyabola.de/

[dyabola.log](https://github.com/emory-libraries/ezpaarse-platforms/files/4042638/dyabola.log)
