### ISSUE TITLE
Fix hraf rtype = 'BOOK_PAGE' 

### ISSUE THREAD

**Issue by AGCooper** [emory-libraries/ezpaarse-platforms#453]
### Example:star::star: :
rtype = 'BOOK_PAGE' is not part of the rtypes

### Priority: 
HIGH

### ezPAARSE
Analysis:
http://ang.couperin.org/platforms/5d49f971ba33347c18b07bd8
Trello:
https://trello.com/c/eFb2csJa/513-human-relations-area-files-hraf

**Comment by AGCooper** [comment]
I see libah saw a BOOK_PAGE rtype but I can't seem to find that. Please let me know where you see that.

**Comment by AGCooper** [comment]
also DATA should be DATASET

**Comment by libah** [comment]
I’ll have to look at it in the morning.

**Comment by libah** [comment]
I was going by the documentation. See this link: https://ezpaarse.readthedocs.io/en/master/essential/ec-attributes.html?highlight=rtype
Scroll down to rtypes. I see now though that it is not in the rtypes.json file for Emory ezpaarse. I think it came up because there were actual book pages in this resource with page numbers. Should I only go by the  Emory rtypes.json file? https://github.com/emory-libraries/ezpaarse-platforms/blob/master/rtype.json

**Comment by AGCooper** [comment]
Okay that sounds good. I'll change DATA to DATASET in production.
