### ISSUE TITLE
Galileo

### ISSUE THREAD

**Issue by eipeele** [emory-libraries/ezpaarse-platforms#49]
### Example:star::star: :
https://login.proxy.library.emory.edu/login?url=http://www.galileo.usg.edu/
https://login.proxy.library.emory.edu/login?url=http://dlg.galileo.usg.edu.
http://discovere.emory.edu/discovere:default_scope:01EMORY_ALMA21240025700002486

### Priority: 
High

### Subscriber (Library): 
Woodruff

**Comment by lisahamlett** [comment]
Couldn't find anything on AnalogIST or Trello.

**Comment by lisahamlett** [comment]
[Galileo Links.txt](https://github.com/emory-libraries/ezpaarse-platforms/files/1697073/Galileo.Links.txt)

**Comment by lisahamlett** [comment]
Nothing on AnalogIST, Trello, or OCLC.
Stanza in ezProxy seems to be up-to-date.

**Comment by CB987** [comment]
DOMAINS
funeral.galileo.usg.edu
dlg.galileo.usg.edu
aafa.galileo.usg.edu
cla.galileo.usg.edu
statregister.galileo.usg.edu
dlgcsm.galileo.usg.edu

SEARCH, HTML
- http://www.galileo.usg.edu:80/scholar/emory/databases/
- http://www.galileo.usg.edu:80/scholar/emory/databases/e/
- http://www.galileo.usg.edu.proxy.library.emory.edu/scholar/emory/types/statistics-datasets/
- http://funeral.galileo.usg.edu:80/funeral/search?subject.normal=dixon&source.page=1
- http://funeral.galileo.usg.edu:80/funeral/search?sort=subject.normal&source.page=1&coverage.location=Athens+Ga
- http://dlg.galileo.usg.edu:80/savannahmayor/date.php
- http://dlg.galileo.usg.edu:80/savannahmayor/mayor.php
- http://aafa.galileo.usg.edu:80/aafa/search?browse-title=first;sort=title
- http://aafa.galileo.usg.edu:80/aafa/search?browse-creator=first;sort=creator
- http://dlg.galileo.usg.edu:80/cgi/bald?query=id:*&numrecs=96&format=_contact&grid=3
- http://cla.galileo.usg.edu:80/cla/search?text=bovine
- http://dlg.galileo.usg.edu:80/cgi/ggpd?action=query&numrecs=25&term_a=librarian&index_a=kt
- http://statregister.galileo.usg.edu:80/statregister/browse/1923_1929.html
- http://statregister.galileo.usg.edu:80/statregister/search?text=librarian
- http://dlg.galileo.usg.edu:80/cgi/gsfr?action=query&term_a=boy&index_a=kw&grid=3&format=_contact
- http://dlg.galileo.usg.edu:80/cgi/gsfr?query=id:*&numrecs=200&format=_contact&grid=3
- http://dlg.galileo.usg.edu:80/cgi/gsfr.cgi?dbs=gsfr&ini=gsfr.ini&userid=public&query=(id%3A+%2A)Date_of_Photo:%221952%22&crumbs=&format=_contact&grid=3
- http://dlg.galileo.usg.edu:80/picturingaugusta/subject.php
-http://dlg.galileo.usg.edu:80/picturingaugusta/contact.php
- http://dlg.galileo.usg.edu:80/dahlonega/author.php
- http://dlg.galileo.usg.edu:80/cgi-bin/sanb.cgi?userid=public&dbs=sanb&ini=sanb.ini&action=display_marked&format=marked
- http://dlg.galileo.usg.edu:80/cgi-bin/vsbg.cgi?userid=public&dbs=vsbg&ini=vsbg.ini&action=display_marked&format=marked
- http://dlg.galileo.usg.edu:80/cgi/vanga?userid=public&dbs=vanga&ini=vanga.ini&action=display_marked&format=marked
- http://dlg.galileo.usg.edu:80/sanborn/CityCounty/Region3.html


TOC, HTML
- http://dlg.galileo.usg.edu:80/georgiamarble/
- http://dlg.galileo.usg.edu:80/douglass/
- http://dlg.galileo.usg.edu:80/jenkins/
- http://dlg.galileo.usg.edu:80/athenswomansclub/
- http://dlg.galileo.usg.edu:80/reed/
- http://dlg.galileo.usg.edu:80/dahlonega/
- http://dlg.galileo.usg.edu:80/cgi-bin/ebind2html.pl/reed_c19
- http://dlg.galileo.usg.edu:80/hargrett/lumpkin/toc.php
- http://dlg.galileo.usg.edu:80/hargrett/toombs/toc
- http://dlg.galileo.usg.edu:80/picturingaugusta/toc.php
-http://dlg.galileo.usg.edu:80/hawkins/toc.php
- http://dlg.galileo.usg.edu:80/hargrett/platter/
- http://dlg.galileo.usg.edu:80/hargrett/williams/   
- http://dlg.galileo.usg.edu:80/hargrett/williams/williams2.php *same resource, same TOC as the one before, but this is page 2, so...? this is another one that has images that don't log. 
- http://dlg.galileo.usg.edu:80/centennialcatalog/y-z.html

REF, HTML
- http://dlg.galileo.usg.edu:80/cgi/bald?userid=public&dbs=bald&ini=bald.ini&action=retrieve&recno=15
- http://dlg.galileo.usg.edu:80/georgiamarble/gmrb001.php
- http://dlg.galileo.usg.edu:80/douglass/dbr079.php
- http://dlg.galileo.usg.edu:80/cgi/ggpd?query=ca:%20(ga%20t700.i5%20m1%201963%20b7)
- http://dlg.galileo.usg.edu:80/cgi/gsfr.cgi?userid=public&dbs=gsfr&ini=gsfr.ini&action=retrieve&rkey=&rset=007&recno=2&numrecs=10&format=_contact&grid=3
- http://dlg.galileo.usg.edu:80/highlander/friended.html
- http://dlg.galileo.usg.edu:80/highlander/attendees.php
- http://dlg.galileo.usg.edu:80/picturingaugusta/aep001.php
- http://dlg.galileo.usg.edu:80/hawkins/figures.php

I'm thinking REF(?), HTML -- these are EADs though if that makes a difference
- http://aafa.galileo.usg.edu:80/aafa/view?docId=ead/aarl90-007-ead.xml;query=;brand=default
- http://aafa.galileo.usg.edu:80/aafa/view?docId=ead/aarl98-008-ead.xml&anchor.id=0

ARTICLE, HTML
- http://dlg.galileo.usg.edu.proxy.library.emory.edu/tornado/exhibit/
- http://cla.galileo.usg.edu:80/cla/view?docId=tei/cla26.xml&query=librarian&brand=default
- http://cla.galileo.usg.edu:80/cla/view?docId=tei/cla3.xml
- http://cla.galileo.usg.edu:80/cla/essay/index.html
- http://dlg.galileo.usg.edu:80/hargrett/platter/001.php
- http://dlg.galileo.usg.edu.proxy.library.emory.edu/jenkins/history.php
- http://dlg.galileo.usg.edu:80/athenswomansclub/awc002.php
- http://dlg.galileo.usg.edu:80/hargrett/lumpkin/jhl0003.php *(this one is actually a transcription of a letter, with the images of the letter so idk if there's a better rtype for it-- figure?-- but also, clicking on the images doesn't produce anything in the proxy log)
- http://dlg.galileo.usg.edu:80/hargrett/toombs/rat001.php    *same as ^
- http://dlg.galileo.usg.edu:80/hawkins/001.php     * same^
- http://dlg.galileo.usg.edu:80/liberty_ships/BuildingLibertyShips/

ARTICLE, PDF
- http://dlg.galileo.usg.edu:80/savannahmayor/pdf/1855.pdf
- http://dlg.galileo.usg.edu:80/savannahmayor/pdf/1894.pdf
- http://dlg.galileo.usg.edu:80/1906catalogue/pdfs/1906_Catalogue.pdf
- http://dlg.galileo.usg.edu:80/ggpd/docs/2018/ga/l412/_ps1/d3/2018_s2_h22/elec_p_btext.con/1.pdf
- http://dlg.galileo.usg.edu:80/ggpd/docs/2019/ga/e480/_ps1/c54/2019/elec_p_btext.con/1.pdf
- http://dlg.galileo.usg.edu:80/statreg-images/pdfs/1923.pdf
- http://dlg.galileo.usg.edu:80/centennialcatalog/pdf/YANCEY_Benjamin_Cudworth.pdf

IMAGE, JPG
- http://funeral.galileo.usg.edu:80/funeral/view?docId=funeral/dixon20040706-001.xml&query=&brand=default
- http://funeral.galileo.usg.edu:80/funeral/view?docId=funeral/johnson19780211-001.xml&query=&brand=default
- http://dlg.galileo.usg.edu:80/cgi/vanga?userid=public&dbs=vanga&ini=vanga.ini&action=display_marked&format=marked
- http://statregister.galileo.usg.edu:80/statregister/view;jsessionid=4949D4748E3C213F43F15961C9E3A023?docId=statregister/stat1971/stat1971-2003.xml&query=librarian&brand=default
- http://dlg.galileo.usg.edu:80/cgi-bin/ebind2html.pl/reed_c05?seq=21
-http://dlgcsm.galib.uga.edu:80/StyleServer/calcrgn?browser=ns&cat=hagp&wid=420&hei=400&style=hagp/hagp.xsl&item=aep001.sid

MAP??!! (or IMAGE), JPEG
- http://dlg.galileo.usg.edu:80/sanborn/CityCounty/Marietta1885/Sheet1.html

BOOK,PDF
- http://dlg.galileo.usg.edu:80/1906catalogue/pdfs/1906_Catalogue.pdf

BOOK_SECTION, PDF
-http://dlg.galileo.usg.edu:80/reed/docs/reed_c19/hi-res/huga-ch19.pdf

BOOK???, HTML (this is confusing because it's a set of images, but clicking on an individual image that comes up as a .jpg doesn't seem to get logged in ezproxy)
- http://dlg.galileo.usg.edu:80/hargrett/barnard/

VIDEO
- http://dlg.galileo.usg.edu:80/georgiamarble/gmrb001/flv/gmrb001.flv
- http://dlg.galileo.usg.edu:80/highlander/flv/efhf01/highlander_new.flv

[galileo.txt](https://github.com/emory-libraries/ezpaarse-platforms/files/3109310/galileo.txt)

**Comment by lisahamlett** [comment]
Some of these links are indistinguishable for type, so I'm going to split the difference.  We can debate the specifics later.  :)
